language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - yarn test
  - yarn run build
  - cp CNAME build/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
